version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    networks:
      - simple_config
    ports:
      - 80:80

  backendserver:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    networks:
      - simple_config
    expose:      
      - 8080

  frontendserver:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    networks:
      - simple_config
    expose:      
      - 3000

networks:
  simple_config: